### ISSUE TITLE
Button to queue whole album

### ISSUE THREAD

**Issue by jensdpersson** [jensdpersson/lystra.html#22]

**Comment by VENTDEV** [comment]
Would be nice if the queue whole album would do a folder recursively. For example I have my music separated by Genre, Artist, Album Type, Album folders.  So if I wanted to add all the albums by artist foo, clicking on the button would add all files recursively in the sub directory.

**Comment by jensdpersson** [comment]
Had to change how the UI works a bit, playlists and tracks are no longer buttons in themselves as they now have more than one action. Moved actions to explicit buttons
