### ISSUE TITLE
Not working with Lighttpd

### ISSUE THREAD

**Issue by VENTDEV** [jensdpersson/lystra.html#23]
Assuming I'm doing this correctly. The script is not working with a default lighttpd install.

I am assuming I just need to put the .html file in a folder and any mp3's in that folder will show up when I navigate to that page. Sadly, nothing shows up. Not even sub folders.

**Comment by jensdpersson** [comment]
Hi, 
thanks for taking the time to open a ticket. 

You will need to enable directory listing in the lighttpd config. 

dir-listing.activate = "enable"

https://www.cyberciti.biz/tips/howto-lighttpd-enable-disable-directory-listing.html

**Comment by VENTDEV** [comment]
Awesome, I got it to list files. You may want to make a note in the readme that directory listing is required. I believe on my actual web server with Apache, I disabled this feature as well. 

It seems to work exactly like how I hoped it would. Except for one small issue, none of the files are playing. Every .mp3 or .ogg comes up in player queue, the proper file name is loaded as the song playing, but the time is always 00:00 / Nan:Nan.

Do you know any additional modules I would need to enable? Or me having the directory simlinked would cause an issue?

Thanks again,
Eric

**Comment by VENTDEV** [comment]
Scratch that, got oggs to load, required Pulse Audio... :\

Mp3's are still nan'd though.

**Comment by VENTDEV** [comment]
And I got mp3's working on my windows computer, so it's entirely browser related on my end. Everything is working, Thanks again!

Eric
