### ISSUE TITLE
Enqueue Infinite Loop

### ISSUE THREAD

**Issue by VENTDEV** [jensdpersson/lystra.html#25]
First off, awesome work so far! I much prefer the buttons to the previous system. I know what the hell I'm clicking when I'm on a mobile OS!

I have a problem though. If I Enqueue a sub directory, eventually it follows the ..'s and Enqueue's everything out of the directory. For example if I have foo/bar/alpha/beta. If I Enqueue alpha, it will do everything in Alpha, beta, then .. (bar) then .. (foo) And so forth.

If it matters, running lighttpd.

**Comment by jensdpersson** [comment]
Thanks for the trouble report. 
I added a manual exclude for ../ links. 
Seems to work. Can you see if it works for you?
thanks.

**Comment by VENTDEV** [comment]
Working wonderfully. This increases usability greatly. Thanks again for your work!
